
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from os.path import isdir
from pathlib import Path
from tkinter import filedialog

from main import present
import os


# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage





OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/calto/build/assets/frame0")
PRESENTATIONS_PATH = './presentations/'


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#353333")

def open_file_dialog():
    file_path = filedialog.askopenfilename(
        title="Select a PowerPoint file",
        filetypes=[("PowerPoint Files", "*.pptx")]
    )
    if file_path:
        print(f"Selected file: {file_path}")
        # Call the function from another file with the selected file path
        window.destroy()
        present(file_path, os.path.isdir(file_path))

canvas = Canvas(
    window,
    bg = "#353333",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

button_image_1 = PhotoImage(
    file=os.path.join('assets', 'frame0', 'button_1.png'))

button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_file_dialog,
    relief="flat"
)
button_1.place(
    x=524.0,
    y=76.0,
    width=258.0,
    height=54.0
)

canvas.create_rectangle(
    85.0,
    152.0,
    1356.0,
    477.0,
    fill="#ACCDFF",
    outline="")

folders = []
for item in os.listdir(PRESENTATIONS_PATH): 
    folders.append(item) 


disp=0
def open_folder(idx):
    window.destroy()
    present(idx, True)


button_image_2 = PhotoImage(
    file=os.path.join('assets', 'frame0', 'button_2.png'))


for i in folders:
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_folder(i),
        relief="flat"
    )
    button_2.place(
        x=177.0+disp,
        y=211.0,
        width=178.0,
        height=163.0
    )

    canvas.create_text(
        241.0+disp,
        395.0,
        anchor="nw",
        text=str(i),
        fill="#000000",
        font=("Inter", 25 * -1)
    )
    disp+=255


image_image_1 = PhotoImage(
    file=os.path.join('assets', 'frame0', 'image_1.png')
)
image_1 = canvas.create_image(
    282.0,
    101.0,
    image=image_image_1
)

button_image_4 = PhotoImage(
    file=os.path.join('assets', 'frame0', 'button_4.png'))

button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1309.0,
    y=25.0,
    width=103.0,
    height=76.0
)

image_image_2 = PhotoImage(
    file=os.path.join('assets', 'frame0', 'image_2.png')
)

image_2 = canvas.create_image(
    721.0,
    745.0,
    image=image_image_2
)
window.resizable(True, True)
window.mainloop()

