
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

import os
from gui_utils import *

from setting_gui import open_setting
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/calto/build/assets/frame0")
PRESENTATIONS_PATH = './presentations/'


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def open_home():
    window = Tk()

    window.geometry("1440x1024")
    window.configure(bg="#353333")

    canvas = Canvas(
        window,
        bg="#353333",
        height=1024,
        width=1440,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)

    button_image_1 = PhotoImage(
        file=os.path.join('assets', 'frame0', 'button_1.png'))

    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_file_dialog(window),
        relief="flat"
    )
    button_1.place(
        x=524.0,
        y=76.0,
        width=258.0,
        height=54.0
    )

    canvas.create_rectangle(
        85.0,
        152.0,
        1356.0,
        477.0,
        fill="#ACCDFF",
        outline="")

    folders = []
    for item in os.listdir(PRESENTATIONS_PATH):
        folders.append(item)

    folder_icon = PhotoImage(
        file=os.path.join('assets', 'frame0', 'button_2.png'))

    show_folder_icons(window, canvas, folder_icon, folders)

    image_image_1 = PhotoImage(
        file=os.path.join('assets', 'frame0', 'image_1.png')
    )
    image_1 = canvas.create_image(
        282.0,
        101.0,
        image=image_image_1
    )

    button_image_4 = PhotoImage(
        file=os.path.join('assets', 'frame0', 'button_4.png'))

    def open_gesture_custom():
        window.destroy()
        open_setting()

    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=open_gesture_custom,
        relief="flat"
    )
    button_4.place(
        x=1309.0,
        y=25.0,
        width=103.0,
        height=76.0
    )

    image_image_2 = PhotoImage(
        file=os.path.join('assets', 'frame0', 'image_2.png')
    )

    image_2 = canvas.create_image(
        721.0,
        745.0,
        image=image_image_2
    )
    window.resizable(True, True)
    window.mainloop()


if __name__ == "__main__":
    open_home()
